# -*- coding: utf-8 -*-
"""Breast Cancer Case Study

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BwYsjhx608800TYvLWbz3ud9tuyTGeYe

# Logistic Regression
####Received data source from UCI Machine Learning Reposistory

## Importing the libraries
"""

import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('breast_cancer.csv')
X = dataset.iloc[:,1:-1]
y = dataset.iloc[:, -1]

print(X)

print(y)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=0)

"""## Training the Logistic Regression model on the Training set"""

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = classifier.predict(X_test)

"""## Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

(84+47)/(84+47+3+3)

# 84 correct prediciton is tumor is benign
# 3 is incorrect predicition is tumer malignant
# 3 is incorrect prediciton is tomer is benign
# 47 is correct prediction is tumer is malignant

"""## Computing the accuracy with k-Fold Cross Validation"""

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator= classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))